name: CI - Assignment-2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: "Printing custom message"
        run: |
          echo "Copied all files into the runner"
